//function call that waits for promises to resolve
//generally, wrap the resulting promise in a try catch to make the code easier to debug
async function asyncFun() {
    try{
        const result = await promise
    }
    catch (error) {

    }
}